package jack.euler.problems.problem2;

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
* */
public class Problem2 {

  public static Long solution() {

    long current = 0;
    long next = 1;
    long fibonacci = 0;
    long sum = 0;

    while (fibonacci < 4000000) {

      fibonacci = current + next;
      current = next;
      next = fibonacci;

      if ((fibonacci & 1) == 0) {
        sum += fibonacci;
      }
    }

    return sum;
  }
}
